# syntax=docker/dockerfile:1

FROM golang:1.21.6

WORKDIR /app

COPY go.mod ./
COPY data ./data
COPY tmpl ./tmpl
COPY *.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /gowtest

EXPOSE 8080

CMD ["/gowtest"]